# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  coolwebapi:
    image: coolwebapi
    build:
      context: .
      dockerfile: CoolWebApi/Dockerfile
    ports:
      - 5232:5232
